import "./globals.css";
import { Inter } from "next/font/google";
import Skeleton, { SkeletonTheme } from "react-loading-skeleton";
import AsideContainer from "./components/AsideContainer";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SkeletonTheme baseColor="#202020" highlightColor="#444">
          <div className="container">
            <AsideContainer />
            <div>
              {children}
            </div>
          </div>
        </SkeletonTheme>
      </body>
    </html>
  );
}
